id = "darker-horizon"
name = "Darker Horizon Theme"
version = "0.0.2"
schema_version = 1
authors = ["ewwwdp <ewwdp@proton.me>"]
description = "Darker Horizon Theme"
repository = "https://github.com/ewwwdp/dark-horizon-zed.git"
